theme: jekyll-theme-minimal
title: Python RESTful API using Flask and MongoDB
logo: https://github.com/gustavo-candido-silva/Python-RESTful-API-using-Flask-and-MongoDB/blob/master/docs/Ilustracao_Sem_Titulo.png
