#!/bin/bash

mkdir logs

chmod +x ~/binder/start.mongodb 
chmod +x ~/binder/start.api

# starting mongodb
~/binder/start.mongodb   &
~/binder/start.api   &

# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
